services:
  zerotrace:
    env_file:
      - .env
    image: ${DOCKER_REGISTRY}/zerotrace-ws:latest
    container_name: zerotrace
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zerotrace.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.zerotrace.entrypoints=websecure"
      - "traefik.http.routers.zerotrace.tls.certresolver=myresolver"
      - "traefik.http.services.zerotrace.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
    environment:
      - NODE_ENV=production

  zerotrace-ws:
    env_file:
      - .env
    image: ${DOCKER_REGISTRY}/zerotrace-ws:latest
    container_name: zerotrace-ws
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zerotrace-ws.rule=Host(`ws.${DOMAIN}`)"
      - "traefik.http.routers.zerotrace-ws.entrypoints=websecure"
      - "traefik.http.routers.zerotrace-ws.tls.certresolver=myresolver"
      - "traefik.http.services.zerotrace-ws.loadbalancer.server.port=8080"
      - "traefik.docker.network=web"
    environment:
      - NODE_ENV=production

networks:
  web:
    name: web
    external: true

